// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvqcHyBC0DPnzFBJSRKlXjpuP8oFSoCNg',
    appId: '1:649108688059:web:7cc2d95acd212439402d9e',
    messagingSenderId: '649108688059',
    projectId: 'ourclinic-6211d',
    authDomain: 'ourclinic-6211d.firebaseapp.com',
    storageBucket: 'ourclinic-6211d.appspot.com',
    measurementId: 'G-E10X5BT58R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDODYfCMZOQOVR99FL2PRj5Y-E8hLfQkSc',
    appId: '1:649108688059:android:e12bb919ef7dc07f402d9e',
    messagingSenderId: '649108688059',
    projectId: 'ourclinic-6211d',
    storageBucket: 'ourclinic-6211d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6KPWxCGwP97Pl8hYalFIvy2ueFLFZDh0',
    appId: '1:649108688059:ios:6aba1b039d71d0fa402d9e',
    messagingSenderId: '649108688059',
    projectId: 'ourclinic-6211d',
    storageBucket: 'ourclinic-6211d.appspot.com',
    iosBundleId: 'com.example.myclinic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6KPWxCGwP97Pl8hYalFIvy2ueFLFZDh0',
    appId: '1:649108688059:ios:15e00489b83934fa402d9e',
    messagingSenderId: '649108688059',
    projectId: 'ourclinic-6211d',
    storageBucket: 'ourclinic-6211d.appspot.com',
    iosBundleId: 'com.example.myclinic.RunnerTests',
  );
}
